C4Context
    title "System context diagram for a CRM system"
    
    Boundary(users, "Пользователи", "") {
        Person(front_office, "Фронт-офис")
        Person(back_office, "Бэк-офис")
        Person(analytics, "Бэк-офис")
        Person(admin, "Административные и технические роли")
    }

    System_Boundary(system, "Пользователи", "") {
        System(crm_system, "CRM - система")
        SystemDb(crm_db, "База данных CRM-системы")
        SystemQueue(crm_broker, "Брокер сообщений CRM-системы")
        
        BiRel(crm_system, crm_db, "")
        BiRel(crm_system, crm_broker, "")
    }



    BiRel(front_office, crm_system, "")
    BiRel(back_office, crm_system, "")
    BiRel(analytics, crm_system, "")
    BiRel(admin, crm_system, "")

    UpdateLayoutConfig($c4ShapeInRow="2", $c4BoundaryInRow="1")
